name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make SnCode better? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the pain point?
      placeholder: I find it frustrating when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like it to work.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the app does this relate to?
      options:
        - Agent / Tools
        - UI / UX
        - Git Integration
        - Skills System
        - Settings / Configuration
        - Packaging / Distribution
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, links, or anything else.
    validations:
      required: false
